### ISSUE TITLE
Generating... no longer proceeds.

### ISSUE THREAD

**Issue by ghost** [zb3/malbolge-tools#2]
I'm interested in malbolge and stumbled upon this program by accident.

At first, I started the GUI in dist. But when I hit Generate it only shows Generating... and it doesn't run anymore.

And I'm trying to convert this program to C language, and I'm curious how randomPool works. Is randomPool simply a variable? Or is it a value encrypted with a certain principle?

**Comment by zb3** [comment]
Does the version at
http://zb3.me/malbolge-tools/
or
https://zb3.me/malbolge-tools/
work for you? I'll look at this tomorrow...

Regarding `randomPool`, while a Malbolge program is a sequence of instructions, some of those are neither executed nor affect memory reads. 

`randomPool` was meant to make it possible to specify instructions to use in these places (they need to be normalized because encoding of an instruction depends on its position in the code and positions of unused/unreferenced instructions are not known ahead of generation). 

So, what's `randomPool`? Oh, that depends. Sometimes this is a string containing normalized ascii representation of Malbolge instructions (or space for random), sometimes this is an array containing a numerical representation of those (or 0 for random).

But like I said, these are used where any Malbolge instruction could be, because it wouldn't affect the program execution in any way.

**Comment by ghost** [comment]
Yes. Going online at https://zb3.me/malbolge-tools/ translates normally.
However, the file in the DIST folder downloaded and executed on the computer did not work properly.

Then, the value of randomPool is as much as the length of 'generator-random-pool' entered online.

```
module.exports.parseRandomPool = function(str) {
   if (!str) return [];

   var t, ret = [];
   for (t = 0; t < str.length; t++)
     ret.push((str[t] === ' ') ? 0 : mb.assembly[str[t]]);
   return ret;
};
```
After this code works, does the returned ret value become a randompool value?

**Comment by zb3** [comment]
So you tried to open the `index.html` file directly? That's not possible in Chrome for security reasons, because web workers and XHR requests are blocked for file-based origins. This means you need to use a server first. If you have Python, just run this in the `dist` directory:
```
python -m http.server
```
then visit [http://localhost:8000/](http://localhost:8000/).

As for the `randomPool`, yes, the value passed to `parseRandomPool` is the content of the `generator-random-pool` element (if enabled). That function then transforms it into an array of Malbolge instruction opcodes. And then that array becomes the new value of `randomPool`:
```javascript
randomPool = gc.parseRandomPool(randomPool)
```

But let me be clear... as you've probably figured out already, this code is absolutely horrible. The variable shouldn't be named like that, it's clearly confusing and the feature is totally useless anyway (by definition).

**Comment by ghost** [comment]
As you said, I started the server by executing the command in Python.
But it didn't work with Chrome and Microsoft Edge, but with internet explorer.

And thanks for the help regarding randomPool!

**Comment by zb3** [comment]
Oh, that's weird, it works for me on Chrome when I go to http://localhost:8000/
Did you see any error message? Is there an error in the Console when you open DevTools (press Ctrl-Shift-I)?

Btw, I didn't even know Internet Explorer still exists :)

**Comment by ghost** [comment]
```
gworker.js:1 Refused to execute script from 'http://localhost:8000/js/generators.js' because its MIME type ('text/plain') is not executable.
(anonymous) @ gworker.js:1

gworker.js:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8000/js/generators.js' failed to load.
    at http://localhost:8000/js/gworker.js:1:1
(anonymous) @ gworker.js:1
```

Following your advice, I checked the console.

The above error code appears.

**Comment by zb3** [comment]
Thanks for providing more info.

I see the Python server is not serving the correct MIME type for `js` files (should be `application/javascript`), and newer browsers need the correct type for... again, security reasons.
This might be a problem with Python on Windows, I'm using Python 3.9.6 on Linux and I see MIME type maps work differently here.

If you have PHP installed, you might try starting a PHP development server in the `dist` directory, like this:
```
php -S localhost:8000
```
I think this should work because this server has its own internal MIME type map and doesn't rely on system-wide maps.

**Comment by ghost** [comment]
Yes. Following the advice, I downloaded XAMPP (PHP Launcher), ran it, and entered the site using localhost.

It works fine. thank you.

**Comment by ghost** [comment]
And I wanted to convert this malbolge tool to python and run it.
However, Python didn't have the features supported by JavaScript, or lacked the time to use it and the ability to crack code.

In the end, in the initial part (gen-liner.js) I created generate (works but not sure if this is correct), generateBoilerplatte, perform_op_mvm and eventually gave up generating the generateStaticText part.

It's a bit disappointing that I couldn't finish the program due to my lack of skills.
Thank you very much for your help and answering my questions.

**Comment by zb3** [comment]
Good to know that's working :)

It's not your fault that you couldn't understand this messy code... Python has all the features needed to write this generator, but I've used some shortcuts which make this code rely on Javascript-specific behaviour and generally hard to understand, _especially_ for beginners.

If you pursue a career in programming, please don't learn from my code, because you'll learn things the wrong way and that could negatively impact your career...

Maybe you should check this one out:
https://github.com/wallstop/MalbolgeGenerator/blob/master/MalbolgeInterpreter.py

I haven't tested it, but it's much more descriptive and easier to understand.
